output-format: pylint

ignore-paths:
    - doc
    - scripts
    - tests

strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

python-targets:
    - 3

uses:
    - django
    - celery
    - flask

dodgy:
    run: true

frosted:
    run: true

mccabe:
    run: true

pydocstyle:
    run: true
    disable:
        - D105 # Missing docstring in magic method
        - D107 # Missing docstring in __init__
        - D200 # One-line docstrings can not fit into more lines
        - D203 # 1 blank line required before class docstring
        - D204 # 1 blank line required after class docstring
        - D205 # 1 blank line required between summary line and description
        - D212 # Multi-line docstring summary should start at the first line
        - F999 # Too many false positive due to type hints

pycodestyle:
    run: false # pylint will check
    full: true
    options:
        max-line-length: 120

profile-validator:
    run: true

pyflakes:
    run: true

pylint:
    run: true

pyroma:
    run: true

vulture:
    run: true
